### ISSUE TITLE
[epic] Protocol 20 SDK Support

### ISSUE THREAD

**Issue by mollykarcher** [stellar/java-stellar-sdk#470]
This epic will be used to track the necessary changes to the SDK/Horizon API pursuant to Soroban / Protocol 20

minimal to support non-breaking compatibility with horizon API: 
 - [ ] Add support for serialization aspects of new Ops, `InvokeHostFunctionOp`, `BumpFootprintExpirationOp`, `RestoreFootprintOp` in api response handlers ([protocol definition](https://github.com/stellar/go/blob/soroban-xdr-next/protocols/horizon/operations/main.go#L348-L358)). #472 
 - [ ] Add/Ensure support for contract addresses (i.e. `C...`). 
   - [ ] valid in `to`/`from` fields in the [`InvokeHostFunctionOp:AssetBalanceChanges` object](https://github.com/stellar/go/blob/soroban-xdr-next/protocols/horizon/operations/main.go#L388). #472 
   - [x] contract/address strkey support - https://github.com/stellar/java-stellar-sdk/pull/471
 - [ ] Add support for new asset stats [fields](https://github.com/stellar/go/blob/soroban-xdr-next/protocols/horizon/main.go#L175-L181): `num_contracts` and `contracts_amount`. https://github.com/stellar/java-stellar-sdk/issues/473

additional functionality for soroban specific contract usage(may move to a separate ticket)
- [ ] Ability to submit Soroban/Protocol 20 Operations in Tx's, BumpFootprintExpirationOp, InvokeHostFunctionOp, RestoreFootprintOp
  - [ ] add support for using soroban rpc to use preflight which is required for the operations. Obtain tx `Ext.SorobanData` and `InvokeHostFunction.Auth` and the required miniumFee, to be included in the tx submitted. refer to js sdk implementation of preflight usage in `prepareTransaction`for example - https://github.com/stellar/js-soroban-client/blob/main/src/server.ts#L526
 - [ ] https://github.com/stellar/java-stellar-sdk/issues/479
 - [ ] add support for contract data `ScVal` conversions to sensible native java types, refer to js sdk's functional implementation of [nativetoScVal and scValToNative](https://github.com/stellar/js-stellar-base/blob/soroban/src/scval.js) for example and scope of conversions, i.e. all the different val types.
 - [ ] add an abstraction such as a pub/sub interface for getting contract events from soroban rpc as a stream.
 - [ ] add test coverage with mocked rpc interface.
 - [ ] add support for fetching contract storage key/value data, refer to js sdk implementation of [getContractData()](https://github.com/stellar/js-soroban-client/blob/main/src/server.ts#L176)

follow the existing go p20/xdr sdk interface conventions.

**Comment by sydneynotthecity** [comment]
@sreuland to review and make more tickets for missing work

**Comment by sreuland** [comment]
closing this epic, #490 will be used going forward for tracking.
